[phases.setup]
nixPkgs = ["python3", "gcc"]
aptPkgs = ["libsqlite3-0"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

# 서버 실행 시 라이브러리 경로를 강제로 지정합니다.
[variables]
LD_LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu"
